////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Community

=== The Source Code

Source code is available on link:https://gitbox.apache.org/repos/asf?p=geronimo-arthur.git[gitbox].

=== Social Media: cause contributing is not only about coding

- link:https://twitter.com/ASFGeronimo[icon:twitter[] Twitter]
- link:https://webchat.freenode.net/?channels=geronimo[icon:terminal[] IRC]

=== Mailing lists

* link:mailto:user-subscribe@geronimo.apache.org[Subscribe] to user@geronimo.apache.org
* link:mailto:user-unsubscribe@geronimo.apache.org[Unsubscribe] from user@geronimo.apache.org
* link:mailto:user@geronimo.apache.org[Post a message] on user@geronimo.apache.org

Archives can be found on link:http://apache-geronimo.328035.n3.nabble.com/[Nabble].

